 - name: startserverservices
   action: service name={{item}} state=started enabled=yes
   with_items:
   - "{{nfsserver}}"
   - "{{nfsrpcbind}}"
   - "{{nfslock}}"
   - "{{nfsidmap}}"
   notify: export nfsshare
 - name: export nfsshare
   shell: exportfs -a
