---
 - hosts: remote1
   user: gvreddy
   become: yes
   gather_facts: yes
   connection: ssh
   pre_tasks:
   - name: date & time stam when playbook start
     command: /usr/bin/date 
     register: timestamp_start
   - debug: var=timestamp_start   
   roles:
   - testrole 
   post_tasks:
   - name: collect playbook end time
     command: /usr/bin/date
     register: timestamp_end
   - debug: var=timestamp_end
